name: CMake Build

on:
  push:
    branches: ["main", "add-workflow"]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        include:
          - os: ubuntu-latest
            lib-ext: so
            exe-ext: ""
            metis-lib: /usr/lib/x86_64-linux-gnu/libmetis.so.5.1.0
            generator: ["Unix Makefiles"]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v5

      - name: Install METIS
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update -q
          sudo apt-get -qy install metis

      - name: Configure
        run: |
          cmake -S . -B build \
            -DCMAKE_INSTALL_PREFIX=install \
            -DMOO_METIS_LIB=${{ matrix.metis-lib }} \
            -DMOO_WITH_GDOPT_EXAMPLE=ON -G "${{ matrix.generator }}"

      - name: Build
        run: cmake --build build --target install

      - name: Run test
        run: ./build/gdopt${{ matrix.exe-ext }}

      - uses: actions/upload-artifact@v4
        with:
          name: install-${{ matrix.os }}
          path: install/
