name: Build

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        generator: ["Unix Makefiles", "Ninja"]

        include:
          - os: ubuntu-latest
            exe-ext: ""
            metis-lib: "-DMOO_METIS_LIB=/usr/lib/x86_64-linux-gnu/libmetis.so.5.1.0"
            lapack-lib: ""

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true

      - name: Install METIS, LAPACK (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update -qq
          sudo apt-get -qqy install metis libblas-dev liblapack-dev gfortran

      - name: Configure
        run: |
          cmake -S . -B build -DCMAKE_INSTALL_PREFIX=install ${{ matrix.metis-lib }} ${{ matrix.lapack-lib }} -DMOO_WITH_GDOPT_EXAMPLE=ON -G "${{ matrix.generator }}"

      - name: Build
        run: cmake --build build --target install

      - name: Run test
        run: ./build/gdopt${{ matrix.exe-ext }}

      - uses: actions/upload-artifact@v4
        with:
          name: install-${{ matrix.os }}-${{ matrix.generator }}
          path: install/
